[2025-10-06T04:12:08.512+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forest_cover_training_pipeline.train_models scheduled__2025-10-06T04:06:00+00:00 [queued]>
[2025-10-06T04:12:08.516+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forest_cover_training_pipeline.train_models scheduled__2025-10-06T04:06:00+00:00 [queued]>
[2025-10-06T04:12:08.517+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-10-06T04:12:08.523+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): train_models> on 2025-10-06 04:06:00+00:00
[2025-10-06T04:12:08.540+0000] {standard_task_runner.py:57} INFO - Started process 4142 to run task
[2025-10-06T04:12:08.543+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'forest_cover_training_pipeline', 'train_models', 'scheduled__2025-10-06T04:06:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline.py', '--cfg-path', '/tmp/tmpo2ziqgal']
[2025-10-06T04:12:08.545+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask train_models
[2025-10-06T04:12:08.574+0000] {task_command.py:416} INFO - Running <TaskInstance: forest_cover_training_pipeline.train_models scheduled__2025-10-06T04:06:00+00:00 [running]> on host 20acfc9d0a87
[2025-10-06T04:12:08.628+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops_team' AIRFLOW_CTX_DAG_ID='forest_cover_training_pipeline' AIRFLOW_CTX_TASK_ID='train_models' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T04:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-06T04:06:00+00:00'
[2025-10-06T04:12:08.983+0000] {logging_mixin.py:154} WARNING - 2025/10/06 04:12:08 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-06T04:12:43.361+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-10-06T04:12:46.780+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.10/site-packages/_distutils_hack/__init__.py:33 UserWarning: Setuptools is replacing distutils.
[2025-10-06T04:12:46.898+0000] {logging_mixin.py:154} WARNING - Registered model 'forest_cover_logistic_regression' already exists. Creating a new version of this model...
[2025-10-06T04:12:46.938+0000] {logging_mixin.py:154} WARNING - 2025/10/06 04:12:46 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_logistic_regression, version 8
[2025-10-06T04:12:46.938+0000] {logging_mixin.py:154} WARNING - Created version '8' of model 'forest_cover_logistic_regression'.
[2025-10-06T04:12:52.199+0000] {logging_mixin.py:154} WARNING - Registered model 'forest_cover_random_forest' already exists. Creating a new version of this model...
[2025-10-06T04:12:52.238+0000] {logging_mixin.py:154} WARNING - 2025/10/06 04:12:52 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_random_forest, version 8
[2025-10-06T04:12:52.238+0000] {logging_mixin.py:154} WARNING - Created version '8' of model 'forest_cover_random_forest'.
[2025-10-06T04:13:10.004+0000] {logging_mixin.py:154} WARNING - Registered model 'forest_cover_gradient_boosting' already exists. Creating a new version of this model...
[2025-10-06T04:13:10.029+0000] {logging_mixin.py:154} WARNING - 2025/10/06 04:13:10 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_gradient_boosting, version 8
[2025-10-06T04:13:10.029+0000] {logging_mixin.py:154} WARNING - Created version '8' of model 'forest_cover_gradient_boosting'.
[2025-10-06T04:13:10.078+0000] {python.py:194} INFO - Done. Returned value was: Entrenados: logistic_regression, random_forest, gradient_boosting
[2025-10-06T04:13:10.094+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=forest_cover_training_pipeline, task_id=train_models, execution_date=20251006T040600, start_date=20251006T041208, end_date=20251006T041310
[2025-10-06T04:13:10.140+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-06T04:13:10.171+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
